# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
gripper:
  type: position_controllers/JointTrajectoryController
  joints:
    - gripper_finger1_joint
    - gripper_finger2_joint
gazebo_ros_control/pid_gains:
  shoulder_pan_joint:  {p: 100, i: 0.01, d: 10.0}
  shoulder_lift_joint:  {p: 100, i: 0.01, d: 10.0}
  elbow_joint:  {p: 100, i: 0.01, d: 10.0}
  wrist_1_joint:  {p: 100, i: 0.01, d: 10.0}
  wrist_2_joint:  {p: 100, i: 0.01, d: 10.0}
  wrist_3_joint:  {p: 100, i: 0.01, d: 10.0}